/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:68578141-4279-404c-aaee-632b9481ba42",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_Qx4t21cDf",
    "aws_user_pools_web_client_id": "7e740msrt8s5bf26lot7vlgu5u",
    "oauth": {}
};


export default awsmobile;
